# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches-ignore:
    - develop
    - release/*
    - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macOS-latest, ubuntu-latest, windows-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
      with:        
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x


    - uses: dotnet/nbgv@master
      id: nbgv

    - name: Diplay Package Version
      run: echo "PackageVersion=${{ steps.nbgv.outputs.SimpleVersion }}-ci.${{ steps.nbgv.outputs.VersionRevision }}"



    - name: Restore dependencies
      run: dotnet restore IdentityServer8.Admin.sln
    - name: Build
      run: dotnet build IdentityServer8.Admin.sln --configuration Release --no-restore -p:Version=${{ steps.nbgv.outputs.SimpleVersion }}-ci.${{ steps.nbgv.outputs.VersionRevision }}
    - name: Test
      run: dotnet test IdentityServer8.Admin.sln --configuration Release --no-build --verbosity normal



